# -*- coding: utf-8 -*-
"""spell_checker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cG2fXsUFq25IkZjVSJ57GtwzhOt5Vjkx
"""

# Install and import libraries
!pip install nltk textblob
import nltk
from textblob import TextBlob

# Download necessary NLTK data
nltk.download('words')

# Function to correct spelling using TextBlob
def correct_spelling(text):
    try:
        blob = TextBlob(text)
        corrected_text = blob.correct()
        return str(corrected_text)  # Ensure output is a string
    except Exception as e:
        return f"Error: {str(e)}"

# Input from user
text = input("Enter the text with spelling errors: ")
print("Original Text:", text)

# Using TextBlob for correction
corrected_text = correct_spelling(text)
print("Corrected Text (TextBlob):", corrected_text)